"""Initial migration

Revision ID: d2f9cc44e715
Revises: 
Create Date: 2025-02-27 12:00:53.435886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f9cc44e715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.alter_column('published_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_column('modified_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('published_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
