"""Added filtering fields

Revision ID: e2cc1c5adb6e
Revises: d2f9cc44e715
Create Date: 2025-02-27 13:22:04.453186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cc1c5adb6e'
down_revision = 'd2f9cc44e715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('published_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('last_modified',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.alter_column('last_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('published_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
